In [3]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array, 다차원배열)


## 리스트를 다차원배열로 변환

In [4]:
# array : 다차원 배열을 만드는 함수
li = [1,2,3,4]
li_arr = np.array(li)

In [5]:
li_arr

array([1, 2, 3, 4])

In [6]:
type(li_arr)

numpy.ndarray

튜플을 다차원배열로 변환

In [7]:
tu = (1,2,3,4)
tu_arr = np.array(tu)

In [8]:
tu_arr

array([1, 2, 3, 4])

In [9]:
type(tu_arr)

numpy.ndarray

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

## float 자료형을 지정해서 다차원 배열 만들기

In [10]:
fl_arr = np.array(li, dtype=float)

In [11]:
fl_arr

array([1., 2., 3., 4.])

In [12]:
fl_arr.dtype

dtype('float64')

## 2차원 배열이란

- 2개의 축을 가지는 배열(행, 열)
    - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [13]:
arr2d = np.array([[1,2,3], [4,5,6]])

In [14]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

- 3개의 원소가 그룹을 이루고 있다, 그 그룹이 2개 뭉쳐져 있는 형상이다 - 3개의 집이 모여 있는 집이 2개의 층으로 쌓여 있다.

In [16]:
# 축의 개수
arr2d.ndim

2

In [17]:
arr2d.dtype

dtype('int32')

In [18]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

## 1차원 배열에서 원소 조회하기

In [19]:
li_arr

array([1, 2, 3, 4])

In [20]:
li_arr[0]

1

In [21]:
li_arr[-1]

4

## 다차원배열에서 원소 조회하기

In [22]:
# 다차원배열을 리스트로 변환
list2d = arr2d.tolist()

In [23]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [24]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱스를 두 번 사용해야함
list2d[0][1]

2

In [27]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0,1]

2

In [28]:
arr2d[0][1]

2

### 슬라이싱

In [29]:
arr1 = np.array([[0,1,2,3], [4,5,6,7]])

In [30]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
# 첫 번째 행(가로) 전체
arr1[0,:] # 0번째 배열의 전체

array([0, 1, 2, 3])

In [32]:
# 두 번째 열(세로) 전체
arr1[:, 1]

array([1, 5])

In [33]:
# 두 번째 행의 두 번째 열부터 끝까지
arr1[1, 1:]

array([5, 6, 7])

In [35]:
#각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

## 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능하다
- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능하다
    - 파이썬 리스트 : 곱셈으로 리스트 요소를 반복하는 것은 가능
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원배열이 필요할 때 사용

# 확인문제

1. 아래의 행렬에서 값 7을 인덱싱
2. 아래의 행렬에서 값 14를 인덱싱
3. 아래의 행렬에서 배열[6,7]을 슬라이싱
4. 아래의 행렬에서 배열[7, 12]를 슬라이싱
5. 아래의 행렬에서 배열 [[3, 4], [8, 9]]를 슬라이싱

In [38]:
m = np.array([[0,1,2, 3, 4],
             [5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14]])

In [39]:
# 1. 값 7을 인덱싱
m[1, 2]

7

In [40]:
# 2. 값 14를 인덱싱
m[2, -1] # [-1, -1], [2, 4]

14

In [41]:
# 3. 배열[6,7]을 슬라이싱
m[1, 1:3]

array([6, 7])

In [43]:
# 4. 배열[7, 12]를 슬라이싱
m[1:3, 2] #[1:, 2]

array([ 7, 12])

In [50]:
# 5. 배열 [[3, 4], [8, 9]]를 슬라이싱
m[0:2, 3:5] # [:2, 3:]

array([[3, 4],
       [8, 9]])

# 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [51]:
arr = np.array([[1,2,3,], [4,5,6]])

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr.shape

(2, 3)

In [54]:
arr.T # T를 붙여서 배열을 일회적으로 바꿈!

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
arr # 원본 데이터는 그대로임!

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr.shape # (행, 열

(2, 3)

In [57]:
arr.T.shape # (행, 열)

(3, 2)

# 배열 크기 변형

In [58]:
arr1 = np.arange(12)

In [59]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
arr2 = arr1.reshape(3, 4)

In [64]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [68]:
arr1.reshape(3, -1) # 한 층에 몇 명씩 넣을지 네가 계산해줘~

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
arr1.reshape(2, 2, -1) # 한 층에 몇 명이 들어갈지는 모르겠는데 2동에 2층짜리를 만들고 싶어~

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [70]:
arr1.reshape(2, -1, 2) # 아파트 2개 동에 한 층에 2개씩 들어갈건데 몇 층인지는 모르겠어 ~

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# 넘파이 함수의 특징

- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함

- 유니버설 함수(Universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [71]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

In [72]:
type(test)

function

In [73]:
# 유니버설 함수 확인
type(np.add)

numpy.ufunc

In [74]:
# 넘파이에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

function

In [76]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [77]:
np.add(list2d, list2d) # 벡터화 연산 = 유니버설 함수

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

### 벡터화 연산이 필요한 이유

- data리스트 내의 각 값에 2를 곱해야 한다면?

In [79]:
data = list(range(10))

In [80]:
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### 리스트를 통한 풀이

In [81]:
data * 2 # 파이썬에서는 리스트 반복된다

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [82]:
ans = []
for i in data:
    ans.append(i * 2)
    
print(ans)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


#### 넘파이를 통한 풀이

In [83]:
data = np.array(data)

In [84]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [85]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [86]:
2 * a + b # (2*a)+b

array([12, 24, 36])

In [87]:
a == 2

array([False,  True, False])

In [88]:
[1, 2, 3] == 2

False

In [89]:
b > 10

array([False,  True,  True])

In [90]:
(a == 2) & (b > 10) # &는 두 개의 값이 T & T 일 때 True로 나타냄

array([False,  True, False])

In [91]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [93]:
arr1 = np.arange(6, 10)

In [94]:
arr1

array([6, 7, 8, 9])

In [95]:
arr2 = np.arange(10, 14)

In [96]:
arr2

array([10, 11, 12, 13])

In [98]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [101]:
# arr1에 차원 추가(수직축 추가)
new_arr1 = arr1[:, np.newaxis]
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [102]:
new_arr1.shape

(4, 1)

In [104]:
# arr2에 차원 추가(수평축 추가)
new_arr2 = arr2[np.newaxis, :]

In [105]:
new_arr2

array([[10, 11, 12, 13]])

In [106]:
new_arr2.shape

(1, 4)

In [108]:
# 행렬곱 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

## 브로드캐스팅(Broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야 함
- 서로 다른 크기를 가진 배열의 사칙연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여서 크기가 큰 배열에 맞춤

In [109]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [110]:
new_arr2

array([[10, 11, 12, 13]])

In [111]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

### 연습문제

1. 아래의 배열에서 3의 배수를 찾으시오
2. 아래의 배열에서 4로 나누면 1이 남는 수를 찾으시오
3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾으시오

In [125]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [129]:
# 3의 배수를 찾으시오
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [126]:
x[2::3]

array([ 3,  6,  9, 12, 15, 18])

In [127]:
# 4로 나누면 1이 남는 수를 찾으시오
x[x % 4 ==1]

array([ 1,  5,  9, 13, 17])

In [130]:
# 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾으시오
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 축에 따른 연산

- 동일한 축에 있는 원소들을 계산하기 위해서 필요함

### 1차원 배열

In [131]:
arr1 = np.array([1, 2, 3, 4])

In [132]:
arr1

array([1, 2, 3, 4])

In [134]:
# 합계
np.sum(arr1)

10

In [135]:
arr1.sum()

10

In [138]:
# 최댓값
arr1.max()

4

In [140]:
# 최솟값
arr1.min()

1

In [141]:
# 최솟값의 위치
arr1.argmin()

0

In [142]:
# 최댓값의 위치
arr1.argmax()

3

In [143]:
# 평균
arr1.mean()

2.5

In [144]:
# 중앙값
np.median(arr1)

2.5

### 2차원 배열

In [145]:
arr2 = arr1.reshape(2, 2)

In [146]:
arr2

array([[1, 2],
       [3, 4]])

In [148]:
# 모든 원소를 더한 합
np.sum(arr2)

10

In [149]:
# 수직방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [150]:
# 수평방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [164]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
arr5.shape

(2, 3)

In [166]:
np.sum(arr5, axis = 0)

array([5, 7, 9])

In [169]:
np.sum(arr5, axis = 1)

array([ 6, 15])

### 3차원 배열

In [151]:
arr3 = np.arange(1, 9)

In [152]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [153]:
arr4 = arr3.reshape(2, 2, 2)

In [154]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [155]:
# 모든 원소를 더한 합
np.sum(arr4)

36

In [156]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr4, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [160]:
# 각 2차원 배열의 열의 합
np.sum(arr4, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [163]:
# 각 2차원 배열의 행의 합
np.sum(arr4, axis = 2)

array([[ 3,  7],
       [11, 15]])

In [175]:
arr6 = np.random.randint(1,10, (2, 3,4))

In [176]:
arr6

array([[[4, 3, 4, 3],
        [7, 2, 5, 2],
        [6, 7, 8, 5]],

       [[9, 4, 8, 1],
        [9, 3, 4, 8],
        [4, 2, 9, 9]]])

In [177]:
arr6.mean(axis = 0)

array([[6.5, 3.5, 6. , 2. ],
       [8. , 2.5, 4.5, 5. ],
       [5. , 4.5, 8.5, 7. ]])

In [178]:
arr6.mean(axis = 1)

array([[5.66666667, 4.        , 5.66666667, 3.33333333],
       [7.33333333, 3.        , 7.        , 6.        ]])

In [179]:
arr6.mean(axis = 2)

array([[3.5, 4. , 6.5],
       [5.5, 6. , 6. ]])

In [180]:
arr6.mean(axis = (0,1))

array([6.5       , 3.5       , 6.33333333, 4.66666667])

In [181]:
arr6.mean(axis = (0, 2)) # 평균값~ (1-1, 2-1) (1-2, 2-2), (1-3,2-3)

array([4.5 , 5.  , 6.25])

In [183]:
arr6.mean(axis = (1, 2)) # 1동 평균, 2동 평균

array([4.66666667, 5.83333333])

#### 연습문제

- 실수로 이루어진 5 x 6 형태의 테이터 행렬을 만들고 다음의 값을 구하시오
    1. 전체의 최댓값
    2. 각 행의 합
    3. 각 행의 최댓값
    4. 각 열의 평균
    5. 각 열의 최솟값

In [188]:
x = np.random.random((5, 6))
x

array([[0.58636488, 0.75745873, 0.27103035, 0.54695014, 0.21630879,
        0.67336169],
       [0.71857145, 0.84571808, 0.07600711, 0.52047856, 0.53534796,
        0.95823207],
       [0.56968025, 0.678506  , 0.53458663, 0.9239768 , 0.13342152,
        0.77277027],
       [0.92198516, 0.75955225, 0.33941253, 0.59622345, 0.03676052,
        0.59480451],
       [0.2121365 , 0.6856046 , 0.63901072, 0.78984627, 0.99594111,
        0.75465195]])

array([[8, 4, 4, 1, 2, 8],
       [4, 8, 8, 6, 4, 7],
       [8, 7, 2, 8, 8, 7],
       [2, 6, 4, 3, 9, 9],
       [5, 1, 9, 7, 2, 2]])

In [189]:
# 1. 전체의 최댓값
x.max()

0.9959411068756128

AxisError: axis 5 is out of bounds for array of dimension 2

AxisError: axis 5 is out of bounds for array of dimension 2

In [194]:
# 2. 각 행의 합
np.sum(x, axis = 1)

array([3.05147457, 3.65435522, 3.61294148, 3.2487384 , 4.07719115])

In [193]:
x.max(axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [200]:
x.sum(axis = 1)

array([3.05147457, 3.65435522, 3.61294148, 3.2487384 , 4.07719115])

In [195]:
# 3. 각 행의 최댓값
np.max(x, axis = 1)

array([0.75745873, 0.95823207, 0.9239768 , 0.92198516, 0.99594111])

In [201]:
x.max(axis = 1)

array([0.75745873, 0.95823207, 0.9239768 , 0.92198516, 0.99594111])

In [198]:
# 4. 각 열의 평균
np.mean(x, axis = 0)

array([0.60174765, 0.74536793, 0.37200947, 0.67549504, 0.38355598,
       0.7507641 ])

In [202]:
x.mean(axis = 0)

array([0.60174765, 0.74536793, 0.37200947, 0.67549504, 0.38355598,
       0.7507641 ])

In [199]:
# 5. 각 열의 최솟값
np.min(x, axis = 0)

array([0.2121365 , 0.678506  , 0.07600711, 0.52047856, 0.03676052,
       0.59480451])

In [203]:
x.min(axis = 0)

array([0.2121365 , 0.678506  , 0.07600711, 0.52047856, 0.03676052,
       0.59480451])

In [204]:
x.argmin(axis = 0)

array([4, 2, 1, 1, 3, 3], dtype=int64)

# Inf와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan이 있음

In [207]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\lg\AppData\Local\Temp\ipykernel_20104\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\lg\AppData\Local\Temp\ipykernel_20104\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

# 스칼라

- 가장 기본적인 값
- 0차원 배열
- 크기를 표현

In [208]:
scalar_arr = np.array(43)

In [210]:
# array에서 스칼라는 대괄호 없이 숫자만 표시
# 대괄호는 벡터(1차원 배열)부터 사용
scalar_arr

array(43)

In [211]:
type(scalar_arr)

numpy.ndarray

In [212]:
# 스칼라는 0차원
scalar_arr.ndim

0

- '[]' 줄을 만들어 주는 개념

In [213]:
# 축이 없기 때문에 shape는 빈 튜플
scalar_arr.shape

()

In [214]:
# array로 스칼라를 만들어도 dtype를 가짐
scalar_arr.dtype

dtype('int32')

# 벡터

- 1차원 배열

In [215]:
vector = np.array([43])

In [216]:
vector

array([43])

In [217]:
type(vector)

numpy.ndarray

In [218]:
# 1차원 배열
vector.ndim # ndim 차원 확인

1

In [220]:
vector.shape # ,가 붙음으로 뒤에 다른 값이 올 수 있다는 것을 나타냄

(1,)

# 배열 생성 함수

## zeros

- 크기가 정해져있고 모든 값이 0인 배열 생성
- 인수로는 배열의 크기를 전달

In [222]:
# 1차원 배열
zero_arr = np.zeros(5)

In [223]:
zero_arr

array([0., 0., 0., 0., 0.])

In [224]:
# 2차원 배열
zero_arr2 = np.zeros((2, 3))

In [226]:
zero_arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

- dtype 인수를 명시하면 해당 자료형 원소 배열을 생성

In [227]:
zero_arr3 = np.zeros((5,2), dtype = int)

In [228]:
zero_arr3

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

## ones

- 모든 값이 1인 배열 생성

In [231]:
one_arr = np.ones((2, 3, 4), dtype = int)
one_arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

## zeros_like, ones_like

- 다른 배열과 같은 크기의 배열을 생성

In [232]:
zero_arr4 = np.zeros_like(one_arr)
zero_arr4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [234]:
one_arr2 = np.ones_like(zero_arr3)
one_arr2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])